const titles = [
  'Great App!',
  'Works great',
  'Amazing!!!!',
  'Loved it!',
  'Liked it ',
  'Nice value for me...',
  'Great choice :D',
  'Recommended',
  'BEATIFUL!!!',
  'Great product!',

  'Works very well',
  'Nice',
  'Works well for me',
  'Thanks',
  'Great app!!!',
  'This app is great!',
  'Took me some time',
  'So far works well',
  'Helped me so much!',
  '5 stars easly...',
  'Nice <3',
  'I would recommend',
  'Fantastic',
  'Very smart',
  'Nice work',
  'recommend it!',
  'LOVE IT <3',
  'Nicely done',
  'I love the design',
  'Been using for a while...',
  'Had to comment',
  'Using latest version',
  'So far so good..',
  'Big like',
  'Well done',
  'Good work, developers',
  'As a premium user',
  'Honest and loyal :)',
  'Very good',
  'Lovely',
  'Productive',
  'No mistakes',
  'The best app ',
  'No issues',
  'Highly recommeneded',
  'Works perfectly fine',
  'AAA+',
  'Amzing and useful',
  'Worth to download',
  '5 Stars',
  'Great developer',
  'Free and useful',
  'Goooooooodddddd',
  'Good job',
  'No complaints',
  'Great update!!',
  'Been using it for few months',
  'litttttt',
  'Liked it a lot',
  'Great and free',
  'Works well',
  'Its freeeeeee',
  'Awesome work',
  'Very useful product',
  'Really loved it',
  'Great!',
  'Niceeeeee',
  'Very useful',
  'Nice app',
  'Fantastic',
  'Works just fime',
  'Its sooo good',
  '5 stars indeed',
  'Works perfectly',
  'deliver the goods',
  'Worth 5 stars',
  'Super useful app',
  'Good overall',
  'More features please',
  'Its OK...',
  'Very well',
  'Awesomeeeee',
  'Very user friendly',
  'So good!!',
  'Great company',
  'Surprisngly great :D',
  "I'm premium for few weeks ",
  'Glad to flatter',
  'It actually works',
  'Free version is legit',
  "I think it's great",
  'Glad I found this app',
  'Great application',
  'Loved the app',
  'Saved my lifeeee',
  'Works beautifully ',
  'Search no more!',
  "It's pretty good",
  'Pretty nice',
];

const texts = [
  'Easy to use, very helpful!',
  "I can't think of of anything wrong with it",
  'This app saved my life and took my breath away at the same damn time',
  'We use this app for everything, we love it.',
  "It's simple and is effective.",
  "I'm happy with so many options.",
  'I have it on all my devices! Love it!',
  'Love using it in my work',
  'I LOVE this app!!! Totally!!',
  'I really enjoy this !',
  "keep doing what you're doing",
  'Much Better than the others',
  'Great app....love this app',
  'I doubt about it at first and could it believe but it work really good',
  'Easy to use. Very friendly, loved the UI',
  'keep up with the good work',
  'Normally I dont write reviews but this time I had to give it a good word',
  'But once you get used to the app its extremely helpful! Worth it.',
  'Does a good job and very easy to use!',
  'Super awesome and I should have installed this app a long time ago',
  'I love it....its cool',
  'Cool love it keep up the good work',
  "It's free and works, worth to download it",
  'Does what it says it does',
  'Nice features, everything I need so far, thanks',
  "I'm happy in so many ways using this app!",
  'Works perfectly fine, love it',
  "I love this app. It's awesome :D",
  'Great app keep up the good work :)',
  'It works and also looks really good I would highly recommend this to anyone.',
  'This is a great app, well built',
  "I have been using this app for a few years. It's time to say its really good guys!!",
  'Stable and easy. I love this.',
  'excellent so far, been using it only for 2 days but so far so good',
  'I like i like I like it lot xoxoxo',
  'Genuinely easy to use',
  'This app is amazing! simple and fun to use',
  'I use this app almost everyday. Very useful',
  "I've been using this app from the early beginning and ever since they launced it its getting better and I really recommend it!",
  'Both my husband and I love this app',
  'Such a wonderful appl',
  'Love it easy to use great tool and features',
  'Does the job, got the pro,, have used many years now, no problems, I the best out there',
  'This app is simply the best',
  'Does what it is meant to do',
  'I use it all the time',
  'Works very nice on my phone',
  'Five stars, would definitely recommend.',
  'Very usefull app. Love it',
  'Would give it 5 stars',
  'Really enjoying it. Cool 5/5',
  'You are gooooood mann u r gooood',
  'This is a must have app',
  'Too good just too good',
  'Awesome app easy to use',
  'Works well with 0 issues',
  "Looking forward! Can't wait to see!",
  'And I am more than satisfied',
  'I very much liked it',
  'Love using it so far',
  'Umm it actually very nice!!',
  "No complaints, totally worth trying, iv'e been using it for serval months now and it's great so far",
  'And I love free :D Hope it stays like that!!',
  'For me, personally, everything works very well and I have nothing but good wors to say, keep up the good work.',
  'Awesome and helpful app. Thanks guys',
  "It's free and works, for me it's more than enough for 5 stars :D",
  'Great and simple app. Truly 5 stars worthy',
  'Perfect!!!!!!!!!!!!!!',
  'Very useful, Upgraded to premium and its worth the money',
  'I just wanted to write a review and say I like it',
  'What a keeper :)',
  'Simple buy does what it says',
  'This app is amazing, thanks!! ',
  'Great....gets the job done',
  "I haven't paid for anything yet and I have all the features I need",
  'Using it since last week, it works as it says',
  'Simple, exactly what I need',
  'Easy to use, i use it everyday!',
  "Over all it's good..",
  'Works well, but could use a few more features',
  "It's good enough for me",
  'Free and most of the time works well',
  "Awesome app, think it's the best our of all the apps I tried",
  'Nice design, simple but very nice',
  'This is just great!!',
  'It works well for all platforms, I have it on all my devices! Love it!',
  "Get it! You won't regret",
  'And honestly I am more than satisfied, I was using the free version for months before and was great as well',
  "I searched for so long for an app that actually works and won't just try to sell me subscriptions all the time...thanks!!",
  "I doubt about it at first and could it believe but it work's",
  'Been using the free version for long time and it works just fine even though I am not premium',
  'It works for me ever since I downloaded it ',
  "I was trying so many apps until I found this one that actually works, highly recommended, don't waste your time on other apps ",
  'I have no words but good ones :D',
  "There's nothing better than find an app that works after so many bad apps",
  'Its tooooooooooooooooooooooooo goooooooooooooooodddddddd',
  "I had an app that I paid for before and It didn't work. This one is free and works better than all the apps I tried",
  'This one actually works!',
  "It's pretty good....",
  "It's very good for a free app",
];

export { titles, texts };
